// 把 src/assets/herdr-skill.md 内联为 src/herdr-skill.ts（JSON 字符串字面量，无转义问题）。
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const md = readFileSync(join(root, 'src/assets/herdr-skill.md'), 'utf8')
const lines = [
  '// Generated by scripts/embed-skill.mjs — DO NOT EDIT BY HAND.',
  '// Source: https://github.com/herdrdev/herdr/blob/v0.8.0/skills/herdr/SKILL.md',
  'export const HERDR_SKILL_MD: string = ' + JSON.stringify(md),
  '',
]
writeFileSync(join(root, 'src/herdr-skill.ts'), lines.join('\n'))
console.log('embedded', md.length, 'chars -> src/herdr-skill.ts')
