/**
 * Generated from herdr api schema (test/fixtures/herdr-api.schema.json).
 * Source: protocol 19, schema_version 1
 * Generated by scripts/gen-types.mjs — DO NOT EDIT BY HAND.
 * Subset (M0): session.snapshot, agent.list, agent.wait, agent.get, agent.explain, pane.split, pane.send_text, pane.send_keys, pane.wait_for_output, pane.read, pane.report_agent, pane.report_metadata, pane.clear_agent_authority, workspace.create, events.subscribe, events.wait, layout.export, layout.apply, notification.show, agent.prompt, agent.send_keys
 */

// ---------- 共享类型（按引用收集） ----------
export interface NotificationShowParams {
  body?: string | null
  position?: ToastHerdrPosition | Record<string, unknown> | null
  sound?: NotificationShowSound
  title: string
}

export type ToastHerdrPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right"

export type NotificationShowSound = "none" | "done" | "request"

export interface EmptyParams {}

export interface WorkspaceCreateParams {
  cwd?: string | null
  env?: { [key: string]: string }
  focus?: boolean
  label?: string | null
}

export interface AgentTarget {
  target: string
}

export interface AgentSendKeysParams {
  keys: string[]
  target: string
}

export interface AgentPromptParams {
  target: string
  text: string
  wait?: AgentPromptWaitOptions | Record<string, unknown> | null
}

export interface AgentPromptWaitOptions {
  timeout_ms?: number | null
  until?: AgentStatus[]
}

export type AgentStatus = "idle" | "working" | "blocked" | "done" | "unknown"

export interface AgentWaitParams {
  target: string
  timeout_ms?: number | null
  until?: AgentStatus[]
}

export interface PaneSplitParams {
  cwd?: string | null
  direction: SplitDirection
  env?: { [key: string]: string }
  focus?: boolean
  ratio?: number | null
  target_pane_id?: string | null
  workspace_id?: string | null
}

export type SplitDirection = "right" | "down"

export interface LayoutExportParams {
  pane_id?: string | null
  tab_id?: string | null
}

export interface LayoutApplyParams {
  focus?: boolean
  root: LayoutNode
  tab_id?: string | null
  tab_label?: string | null
  workspace_id?: string | null
}

export type LayoutNode = {
  command?: string[] | null
  cwd?: string | null
  env?: { [key: string]: string }
  label?: string | null
  pane_id?: string | null
  type: "pane"
} | {
  direction: SplitDirection
  first: LayoutNode
  ratio: number
  second: LayoutNode
  type: "split"
}

export interface PaneSendTextParams {
  pane_id: string
  text: string
}

export interface PaneSendKeysParams {
  keys: string[]
  pane_id: string
}

export interface PaneReadParams {
  format?: ReadFormat
  lines?: number | null
  pane_id: string
  source: ReadSource
  strip_ansi?: boolean
}

export type ReadFormat = "text" | "ansi"

export type ReadSource = "visible" | "recent" | "recent_unwrapped" | "detection"

export interface PaneReportAgentParams {
  agent: string
  agent_session_id?: string | null
  agent_session_path?: string | null
  message?: string | null
  pane_id: string
  seq?: number | null
  source: string
  state: PaneAgentState
}

export type PaneAgentState = "idle" | "working" | "blocked" | "unknown"

export interface PaneReportMetadataParams {
  agent?: string | null
  applies_to_source?: string | null
  clear_display_agent?: boolean
  clear_state_labels?: boolean
  clear_title?: boolean
  display_agent?: string | null
  pane_id: string
  seq?: number | null
  source: string
  state_labels?: { [key: string]: string }
  title?: string | null
  tokens?: { [key: string]: string | null }
  ttl_ms?: number | null
}

export interface PaneClearAgentAuthorityParams {
  pane_id: string
  seq?: number | null
  source?: string | null
}

export interface EventsSubscribeParams {
  subscriptions: Subscription[]
}

export type Subscription = {
  type: "workspace.created"
} | {
  type: "workspace.updated"
} | {
  type: "workspace.metadata_updated"
} | {
  type: "workspace.renamed"
} | {
  type: "workspace.moved"
} | {
  type: "workspace.reordered"
} | {
  type: "workspace.closed"
} | {
  type: "workspace.focused"
} | {
  type: "worktree.created"
} | {
  type: "worktree.opened"
} | {
  type: "worktree.removed"
} | {
  type: "tab.created"
} | {
  type: "tab.closed"
} | {
  type: "tab.focused"
} | {
  type: "tab.renamed"
} | {
  type: "tab.moved"
} | {
  type: "pane.created"
} | {
  type: "pane.closed"
} | {
  type: "pane.updated"
} | {
  type: "pane.focused"
} | {
  type: "pane.moved"
} | {
  type: "pane.exited"
} | {
  type: "pane.agent_detected"
} | {
  lines?: number | null
  match: OutputMatch
  pane_id: string
  source: ReadSource
  strip_ansi?: boolean
  type: "pane.output_matched"
} | {
  agent_status?: AgentStatus | Record<string, unknown> | null
  pane_id: string
  type: "pane.agent_status_changed"
} | {
  pane_id: string
  type: "pane.scroll_changed"
} | {
  type: "layout.updated"
}

export type OutputMatch = {
  type: "substring"
  value: string
} | {
  type: "regex"
  value: string
}

export interface EventsWaitParams {
  match_event: EventMatch
  timeout_ms?: number | null
}

export type EventMatch = {
  event: "workspace_created"
  workspace_id?: string | null
} | {
  event: "workspace_updated"
  workspace_id: string
} | {
  event: "workspace_closed"
  workspace_id: string
} | {
  event: "workspace_renamed"
  label?: string | null
  workspace_id: string
} | {
  event: "workspace_moved"
  workspace_id: string
} | {
  event: "workspace_focused"
  workspace_id: string
} | {
  event: "tab_created"
  tab_id?: string | null
  workspace_id?: string | null
} | {
  event: "tab_closed"
  tab_id: string
} | {
  event: "tab_renamed"
  label?: string | null
  tab_id: string
} | {
  event: "tab_moved"
  tab_id: string
} | {
  event: "tab_focused"
  tab_id: string
} | {
  event: "pane_created"
  pane_id?: string | null
  workspace_id?: string | null
} | {
  event: "pane_closed"
  pane_id: string
} | {
  event: "pane_focused"
  pane_id: string
} | {
  event: "pane_moved"
  pane_id: string
} | {
  event: "pane_output_changed"
  min_revision?: number | null
  pane_id: string
} | {
  event: "pane_exited"
  pane_id: string
} | {
  agent?: string | null
  event: "pane_agent_detected"
  pane_id: string
} | {
  agent_status: AgentStatus
  event: "pane_agent_status_changed"
  pane_id: string
}

export interface PaneWaitForOutputParams {
  lines?: number | null
  match: OutputMatch
  pane_id: string
  source: ReadSource
  strip_ansi?: boolean
  timeout_ms?: number | null
}

// ---------- 方法参数 ----------
// notification.show -> NotificationShowParams（已在上方共享类型中声明）
// session.snapshot -> EmptyParams（已在上方共享类型中声明）
// workspace.create -> WorkspaceCreateParams（已在上方共享类型中声明）
// agent.list -> EmptyParams（已在上方共享类型中声明）
// agent.get -> AgentTarget（已在上方共享类型中声明）
// agent.explain -> AgentTarget（已在上方共享类型中声明）
// agent.send_keys -> AgentSendKeysParams（已在上方共享类型中声明）
// agent.prompt -> AgentPromptParams（已在上方共享类型中声明）
// agent.wait -> AgentWaitParams（已在上方共享类型中声明）
// pane.split -> PaneSplitParams（已在上方共享类型中声明）
// layout.export -> LayoutExportParams（已在上方共享类型中声明）
// layout.apply -> LayoutApplyParams（已在上方共享类型中声明）
// pane.send_text -> PaneSendTextParams（已在上方共享类型中声明）
// pane.send_keys -> PaneSendKeysParams（已在上方共享类型中声明）
// pane.read -> PaneReadParams（已在上方共享类型中声明）
// pane.report_agent -> PaneReportAgentParams（已在上方共享类型中声明）
// pane.report_metadata -> PaneReportMetadataParams（已在上方共享类型中声明）
// pane.clear_agent_authority -> PaneClearAgentAuthorityParams（已在上方共享类型中声明）
// events.subscribe -> EventsSubscribeParams（已在上方共享类型中声明）
// events.wait -> EventsWaitParams（已在上方共享类型中声明）
// pane.wait_for_output -> PaneWaitForOutputParams（已在上方共享类型中声明）
// ---------- 请求映射 ----------
export interface HerdrRequestMap {
  'notification.show': { method: 'notification.show'; params: NotificationShowParams }
  'session.snapshot': { method: 'session.snapshot'; params: EmptyParams }
  'workspace.create': { method: 'workspace.create'; params: WorkspaceCreateParams }
  'agent.list': { method: 'agent.list'; params: EmptyParams }
  'agent.get': { method: 'agent.get'; params: AgentTarget }
  'agent.explain': { method: 'agent.explain'; params: AgentTarget }
  'agent.send_keys': { method: 'agent.send_keys'; params: AgentSendKeysParams }
  'agent.prompt': { method: 'agent.prompt'; params: AgentPromptParams }
  'agent.wait': { method: 'agent.wait'; params: AgentWaitParams }
  'pane.split': { method: 'pane.split'; params: PaneSplitParams }
  'layout.export': { method: 'layout.export'; params: LayoutExportParams }
  'layout.apply': { method: 'layout.apply'; params: LayoutApplyParams }
  'pane.send_text': { method: 'pane.send_text'; params: PaneSendTextParams }
  'pane.send_keys': { method: 'pane.send_keys'; params: PaneSendKeysParams }
  'pane.read': { method: 'pane.read'; params: PaneReadParams }
  'pane.report_agent': { method: 'pane.report_agent'; params: PaneReportAgentParams }
  'pane.report_metadata': { method: 'pane.report_metadata'; params: PaneReportMetadataParams }
  'pane.clear_agent_authority': { method: 'pane.clear_agent_authority'; params: PaneClearAgentAuthorityParams }
  'events.subscribe': { method: 'events.subscribe'; params: EventsSubscribeParams }
  'events.wait': { method: 'events.wait'; params: EventsWaitParams }
  'pane.wait_for_output': { method: 'pane.wait_for_output'; params: PaneWaitForOutputParams }
}

export type HerdrMethod = keyof HerdrRequestMap
