/**
 * Generated from herdr api schema (test/fixtures/herdr-api.schema.json).
 * Source: protocol 19, schema_version 1
 * Generated by scripts/gen-types.mjs — DO NOT EDIT BY HAND.
 * Subset (M0): session.snapshot, agent.list, agent.wait, agent.get, agent.explain, pane.split, pane.send_text, pane.send_keys, pane.wait_for_output, pane.read, pane.report_agent, pane.report_metadata, pane.clear_agent_authority, workspace.create, events.subscribe, events.wait, layout.export, layout.apply, notification.show, agent.prompt, agent.send_keys
 * Sections: params / result branches / error / event / subscription event
 */

// ---------- 共享类型（按引用收集） ----------
export interface NotificationShowParams {
  body?: string | null
  position?: ToastHerdrPosition | Record<string, unknown> | null
  sound?: NotificationShowSound
  title: string
}

export type ToastHerdrPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right"

export type NotificationShowSound = "none" | "done" | "request"

export interface EmptyParams {}

export interface WorkspaceCreateParams {
  cwd?: string | null
  env?: { [key: string]: string }
  focus?: boolean
  label?: string | null
}

export interface AgentTarget {
  target: string
}

export interface AgentSendKeysParams {
  keys: string[]
  target: string
}

export interface AgentPromptParams {
  target: string
  text: string
  wait?: AgentPromptWaitOptions | Record<string, unknown> | null
}

export interface AgentPromptWaitOptions {
  timeout_ms?: number | null
  until?: AgentStatus[]
}

export type AgentStatus = "idle" | "working" | "blocked" | "done" | "unknown"

export interface AgentWaitParams {
  target: string
  timeout_ms?: number | null
  until?: AgentStatus[]
}

export interface PaneSplitParams {
  cwd?: string | null
  direction: SplitDirection
  env?: { [key: string]: string }
  focus?: boolean
  ratio?: number | null
  target_pane_id?: string | null
  workspace_id?: string | null
}

export type SplitDirection = "right" | "down"

export interface LayoutExportParams {
  pane_id?: string | null
  tab_id?: string | null
}

export interface LayoutApplyParams {
  focus?: boolean
  root: LayoutNode
  tab_id?: string | null
  tab_label?: string | null
  workspace_id?: string | null
}

export type LayoutNode = {
  command?: string[] | null
  cwd?: string | null
  env?: { [key: string]: string }
  label?: string | null
  pane_id?: string | null
  type: "pane"
} | {
  direction: SplitDirection
  first: LayoutNode
  ratio: number
  second: LayoutNode
  type: "split"
}

export interface PaneSendTextParams {
  pane_id: string
  text: string
}

export interface PaneSendKeysParams {
  keys: string[]
  pane_id: string
}

export interface PaneReadParams {
  format?: ReadFormat
  lines?: number | null
  pane_id: string
  source: ReadSource
  strip_ansi?: boolean
}

export type ReadFormat = "text" | "ansi"

export type ReadSource = "visible" | "recent" | "recent_unwrapped" | "detection"

export interface PaneReportAgentParams {
  agent: string
  agent_session_id?: string | null
  agent_session_path?: string | null
  message?: string | null
  pane_id: string
  seq?: number | null
  source: string
  state: PaneAgentState
}

export type PaneAgentState = "idle" | "working" | "blocked" | "unknown"

export interface PaneReportMetadataParams {
  agent?: string | null
  applies_to_source?: string | null
  clear_display_agent?: boolean
  clear_state_labels?: boolean
  clear_title?: boolean
  display_agent?: string | null
  pane_id: string
  seq?: number | null
  source: string
  state_labels?: { [key: string]: string }
  title?: string | null
  tokens?: { [key: string]: string | null }
  ttl_ms?: number | null
}

export interface PaneClearAgentAuthorityParams {
  pane_id: string
  seq?: number | null
  source?: string | null
}

export interface EventsSubscribeParams {
  subscriptions: Subscription[]
}

export type Subscription = {
  type: "workspace.created"
} | {
  type: "workspace.updated"
} | {
  type: "workspace.metadata_updated"
} | {
  type: "workspace.renamed"
} | {
  type: "workspace.moved"
} | {
  type: "workspace.reordered"
} | {
  type: "workspace.closed"
} | {
  type: "workspace.focused"
} | {
  type: "worktree.created"
} | {
  type: "worktree.opened"
} | {
  type: "worktree.removed"
} | {
  type: "tab.created"
} | {
  type: "tab.closed"
} | {
  type: "tab.focused"
} | {
  type: "tab.renamed"
} | {
  type: "tab.moved"
} | {
  type: "pane.created"
} | {
  type: "pane.closed"
} | {
  type: "pane.updated"
} | {
  type: "pane.focused"
} | {
  type: "pane.moved"
} | {
  type: "pane.exited"
} | {
  type: "pane.agent_detected"
} | {
  lines?: number | null
  match: OutputMatch
  pane_id: string
  source: ReadSource
  strip_ansi?: boolean
  type: "pane.output_matched"
} | {
  agent_status?: AgentStatus | Record<string, unknown> | null
  pane_id: string
  type: "pane.agent_status_changed"
} | {
  pane_id: string
  type: "pane.scroll_changed"
} | {
  type: "layout.updated"
}

export type OutputMatch = {
  type: "substring"
  value: string
} | {
  type: "regex"
  value: string
}

export interface EventsWaitParams {
  match_event: EventMatch
  timeout_ms?: number | null
}

export type EventMatch = {
  event: "workspace_created"
  workspace_id?: string | null
} | {
  event: "workspace_updated"
  workspace_id: string
} | {
  event: "workspace_closed"
  workspace_id: string
} | {
  event: "workspace_renamed"
  label?: string | null
  workspace_id: string
} | {
  event: "workspace_moved"
  workspace_id: string
} | {
  event: "workspace_focused"
  workspace_id: string
} | {
  event: "tab_created"
  tab_id?: string | null
  workspace_id?: string | null
} | {
  event: "tab_closed"
  tab_id: string
} | {
  event: "tab_renamed"
  label?: string | null
  tab_id: string
} | {
  event: "tab_moved"
  tab_id: string
} | {
  event: "tab_focused"
  tab_id: string
} | {
  event: "pane_created"
  pane_id?: string | null
  workspace_id?: string | null
} | {
  event: "pane_closed"
  pane_id: string
} | {
  event: "pane_focused"
  pane_id: string
} | {
  event: "pane_moved"
  pane_id: string
} | {
  event: "pane_output_changed"
  min_revision?: number | null
  pane_id: string
} | {
  event: "pane_exited"
  pane_id: string
} | {
  agent?: string | null
  event: "pane_agent_detected"
  pane_id: string
} | {
  agent_status: AgentStatus
  event: "pane_agent_status_changed"
  pane_id: string
}

export interface PaneWaitForOutputParams {
  lines?: number | null
  match: OutputMatch
  pane_id: string
  source: ReadSource
  strip_ansi?: boolean
  timeout_ms?: number | null
}

export interface SessionSnapshot {
  agents: AgentInfo[]
  focused_pane_id?: string | null
  focused_tab_id?: string | null
  focused_workspace_id?: string | null
  layouts: PaneLayoutSnapshot[]
  panes: PaneInfo[]
  protocol: number
  tabs: TabInfo[]
  version: string
  workspaces: WorkspaceInfo[]
}

export interface AgentInfo {
  agent?: string | null
  agent_session?: AgentSessionInfo | Record<string, unknown> | null
  agent_status: AgentStatus
  cwd?: string | null
  display_agent?: string | null
  focused: boolean
  foreground_cwd?: string | null
  interactive_ready?: boolean
  launch_pending?: boolean
  name?: string | null
  pane_id: string
  revision: number
  screen_detection_skipped?: boolean
  state_change_seq?: number
  state_labels?: { [key: string]: string }
  tab_id: string
  terminal_id: string
  terminal_title?: string | null
  terminal_title_stripped?: string | null
  title?: string | null
  tokens?: { [key: string]: string }
  workspace_id: string
}

export interface AgentSessionInfo {
  agent: string
  kind: AgentSessionRefKind
  source: string
  value: string
}

export type AgentSessionRefKind = "id" | "path"

export interface PaneLayoutSnapshot {
  area: PaneLayoutRect
  focused_pane_id: string
  panes: PaneLayoutPane[]
  splits: PaneLayoutSplit[]
  tab_id: string
  workspace_id: string
  zoomed: boolean
}

export interface PaneLayoutRect {
  height: number
  width: number
  x: number
  y: number
}

export interface PaneLayoutPane {
  focused: boolean
  pane_id: string
  rect: PaneLayoutRect
}

export interface PaneLayoutSplit {
  direction: SplitDirection
  id: string
  ratio: number
  rect: PaneLayoutRect
}

export interface PaneInfo {
  agent?: string | null
  agent_session?: AgentSessionInfo | Record<string, unknown> | null
  agent_status: AgentStatus
  cwd?: string | null
  display_agent?: string | null
  focused: boolean
  foreground_cwd?: string | null
  label?: string | null
  pane_id: string
  revision: number
  scroll?: PaneScrollInfo | Record<string, unknown> | null
  state_labels?: { [key: string]: string }
  tab_id: string
  terminal_id: string
  terminal_title?: string | null
  terminal_title_stripped?: string | null
  title?: string | null
  tokens?: { [key: string]: string }
  workspace_id: string
}

export interface PaneScrollInfo {
  max_offset_from_bottom: number
  offset_from_bottom: number
  viewport_rows: number
}

export interface TabInfo {
  agent_status: AgentStatus
  focused: boolean
  label: string
  number: number
  pane_count: number
  tab_id: string
  workspace_id: string
}

export interface WorkspaceInfo {
  active_tab_id: string
  agent_status: AgentStatus
  focused: boolean
  label: string
  number: number
  pane_count: number
  tab_count: number
  tokens?: { [key: string]: string }
  workspace_id: string
  worktree?: WorkspaceWorktreeInfo | Record<string, unknown> | null
}

export interface WorkspaceWorktreeInfo {
  checkout_path: string
  is_linked_worktree: boolean
  repo_key: string
  repo_name: string
  repo_root: string
}

export interface PaneReadResult {
  format: ReadFormat
  pane_id: string
  revision: number
  source: ReadSource
  tab_id: string
  text: string
  truncated: boolean
  workspace_id: string
}

export interface EventEnvelope {
  data: EventData
  event: EventKind
}

export type EventData = {
  type: "workspace_created"
  workspace: WorkspaceInfo
} | {
  type: "workspace_updated"
  workspace: WorkspaceInfo
} | {
  type: "workspace_metadata_updated"
  workspace: WorkspaceInfo
} | {
  type: "workspace_closed"
  workspace?: WorkspaceInfo | Record<string, unknown> | null
  workspace_id: string
} | {
  label: string
  type: "workspace_renamed"
  workspace_id: string
} | {
  insert_index: number
  type: "workspace_moved"
  workspace_id: string
  workspaces: WorkspaceInfo[]
} | {
  before_workspace_id?: string | null
  type: "workspace_reordered"
  workspace_ids: string[]
  workspaces: WorkspaceInfo[]
} | {
  type: "workspace_focused"
  workspace_id: string
} | {
  type: "worktree_created"
  workspace: WorkspaceInfo
  worktree: WorktreeInfo
} | {
  already_open: boolean
  type: "worktree_opened"
  workspace: WorkspaceInfo
  worktree: WorktreeInfo
} | {
  forced: boolean
  type: "worktree_removed"
  workspace?: WorkspaceInfo | Record<string, unknown> | null
  workspace_id: string
  worktree: WorktreeInfo
} | {
  tab: TabInfo
  type: "tab_created"
} | {
  tab_id: string
  type: "tab_closed"
  workspace_id: string
} | {
  label: string
  tab_id: string
  type: "tab_renamed"
  workspace_id: string
} | {
  insert_index: number
  tab_id: string
  tabs: TabInfo[]
  type: "tab_moved"
  workspace_id: string
} | {
  tab_id: string
  type: "tab_focused"
  workspace_id: string
} | {
  pane: PaneInfo
  type: "pane_created"
} | {
  pane_id: string
  type: "pane_closed"
  workspace_id: string
} | {
  pane: PaneInfo
  type: "pane_updated"
} | {
  pane_id: string
  type: "pane_focused"
  workspace_id: string
} | {
  closed_tab_id?: string | null
  closed_workspace_id?: string | null
  created_tab?: TabInfo | Record<string, unknown> | null
  created_workspace?: WorkspaceInfo | Record<string, unknown> | null
  pane: PaneInfo
  previous_pane_id: string
  previous_tab_id: string
  previous_workspace_id: string
  type: "pane_moved"
} | {
  pane_id: string
  revision: number
  type: "pane_output_changed"
  workspace_id: string
} | {
  pane_id: string
  type: "pane_exited"
  workspace_id: string
} | {
  agent?: string | null
  final_status?: AgentStatus | Record<string, unknown> | null
  pane_id: string
  released?: boolean
  type: "pane_agent_detected"
  workspace_id: string
} | {
  agent?: string | null
  agent_status: AgentStatus
  display_agent?: string | null
  pane_id: string
  state_labels?: { [key: string]: string }
  title?: string | null
  type: "pane_agent_status_changed"
  workspace_id: string
} | {
  layout: PaneLayoutSnapshot
  type: "layout_updated"
}

export interface WorktreeInfo {
  branch?: string | null
  is_bare: boolean
  is_detached: boolean
  is_linked_worktree: boolean
  is_prunable: boolean
  label: string
  open_workspace_id?: string | null
  path: string
}

export type EventKind = "workspace_created" | "workspace_updated" | "workspace_metadata_updated" | "workspace_closed" | "workspace_renamed" | "workspace_moved" | "workspace_reordered" | "workspace_focused" | "worktree_created" | "worktree_opened" | "worktree_removed" | "tab_created" | "tab_closed" | "tab_renamed" | "tab_moved" | "tab_focused" | "pane_created" | "pane_closed" | "pane_updated" | "pane_focused" | "pane_moved" | "pane_output_changed" | "pane_exited" | "pane_agent_detected" | "pane_agent_status_changed" | "layout_updated"

export interface LayoutDescription {
  focused_pane_id: string
  root: LayoutNode
  tab_id: string
  workspace_id: string
  zoomed: boolean
}

export type NotificationShowReason = "shown" | "disabled" | "rate_limited" | "no_foreground_client" | "busy"

export interface PaneOutputMatchedEvent {
  matched_line: string
  pane_id: string
  read: PaneReadResult
}

export interface PaneAgentStatusChangedEvent {
  agent?: string | null
  agent_status: AgentStatus
  display_agent?: string | null
  pane_id: string
  state_labels?: { [key: string]: string }
  title?: string | null
  workspace_id: string
}

export interface PaneScrollChangedEvent {
  pane_id: string
  scroll: PaneScrollInfo
  workspace_id: string
}

// ---------- 方法参数 ----------
// notification.show -> NotificationShowParams（已在上方共享类型中声明）
// session.snapshot -> EmptyParams（已在上方共享类型中声明）
// workspace.create -> WorkspaceCreateParams（已在上方共享类型中声明）
// agent.list -> EmptyParams（已在上方共享类型中声明）
// agent.get -> AgentTarget（已在上方共享类型中声明）
// agent.explain -> AgentTarget（已在上方共享类型中声明）
// agent.send_keys -> AgentSendKeysParams（已在上方共享类型中声明）
// agent.prompt -> AgentPromptParams（已在上方共享类型中声明）
// agent.wait -> AgentWaitParams（已在上方共享类型中声明）
// pane.split -> PaneSplitParams（已在上方共享类型中声明）
// layout.export -> LayoutExportParams（已在上方共享类型中声明）
// layout.apply -> LayoutApplyParams（已在上方共享类型中声明）
// pane.send_text -> PaneSendTextParams（已在上方共享类型中声明）
// pane.send_keys -> PaneSendKeysParams（已在上方共享类型中声明）
// pane.read -> PaneReadParams（已在上方共享类型中声明）
// pane.report_agent -> PaneReportAgentParams（已在上方共享类型中声明）
// pane.report_metadata -> PaneReportMetadataParams（已在上方共享类型中声明）
// pane.clear_agent_authority -> PaneClearAgentAuthorityParams（已在上方共享类型中声明）
// events.subscribe -> EventsSubscribeParams（已在上方共享类型中声明）
// events.wait -> EventsWaitParams（已在上方共享类型中声明）
// pane.wait_for_output -> PaneWaitForOutputParams（已在上方共享类型中声明）
// ---------- 请求映射 ----------
export interface HerdrRequestMap {
  'notification.show': { method: 'notification.show'; params: NotificationShowParams }
  'session.snapshot': { method: 'session.snapshot'; params: EmptyParams }
  'workspace.create': { method: 'workspace.create'; params: WorkspaceCreateParams }
  'agent.list': { method: 'agent.list'; params: EmptyParams }
  'agent.get': { method: 'agent.get'; params: AgentTarget }
  'agent.explain': { method: 'agent.explain'; params: AgentTarget }
  'agent.send_keys': { method: 'agent.send_keys'; params: AgentSendKeysParams }
  'agent.prompt': { method: 'agent.prompt'; params: AgentPromptParams }
  'agent.wait': { method: 'agent.wait'; params: AgentWaitParams }
  'pane.split': { method: 'pane.split'; params: PaneSplitParams }
  'layout.export': { method: 'layout.export'; params: LayoutExportParams }
  'layout.apply': { method: 'layout.apply'; params: LayoutApplyParams }
  'pane.send_text': { method: 'pane.send_text'; params: PaneSendTextParams }
  'pane.send_keys': { method: 'pane.send_keys'; params: PaneSendKeysParams }
  'pane.read': { method: 'pane.read'; params: PaneReadParams }
  'pane.report_agent': { method: 'pane.report_agent'; params: PaneReportAgentParams }
  'pane.report_metadata': { method: 'pane.report_metadata'; params: PaneReportMetadataParams }
  'pane.clear_agent_authority': { method: 'pane.clear_agent_authority'; params: PaneClearAgentAuthorityParams }
  'events.subscribe': { method: 'events.subscribe'; params: EventsSubscribeParams }
  'events.wait': { method: 'events.wait'; params: EventsWaitParams }
  'pane.wait_for_output': { method: 'pane.wait_for_output'; params: PaneWaitForOutputParams }
}

export type HerdrMethod = keyof HerdrRequestMap

// ---------- 响应结果分支（CA-004） ----------
// session.snapshot -> session_snapshot
export interface SessionSnapshotResult {
  snapshot: SessionSnapshot
  type: "session_snapshot"
}

// agent.list -> agent_list
export interface AgentListResult {
  agents: AgentInfo[]
  type: "agent_list"
}

// agent.get -> agent_view
export interface AgentViewResult {
  active: boolean
  label?: string | null
  source?: string | null
  type: "agent_view"
}

// agent.wait -> agent_info
export interface AgentInfoResult {
  agent: AgentInfo
  type: "agent_info"
}

// agent.explain -> agent_explain
export interface AgentExplainResult {
  explain: unknown
  type: "agent_explain"
}

// agent.prompt -> agent_prompted
export interface AgentPromptedResult {
  agent: AgentInfo
  type: "agent_prompted"
}

// agent.send_keys -> ok
export interface OkResult {
  type: "ok"
}

// pane.split -> pane_info
export interface PaneInfoResult {
  pane: PaneInfo
  type: "pane_info"
}

// pane.send_text -> ok
// pane.send_keys -> ok
// pane.read -> pane_read
export interface PaneReadBranchResult {
  read: PaneReadResult
  type: "pane_read"
}

// pane.wait_for_output -> output_matched
export interface OutputMatchedResult {
  matched_line?: string | null
  pane_id: string
  read: PaneReadResult
  revision: number
  type: "output_matched"
}

// pane.report_agent -> ok
// pane.report_metadata -> ok
// pane.clear_agent_authority -> ok
// workspace.create -> workspace_created
export interface WorkspaceCreatedResult {
  root_pane: PaneInfo
  tab: TabInfo
  type: "workspace_created"
  workspace: WorkspaceInfo
}

// events.subscribe -> subscription_started
export interface SubscriptionStartedResult {
  type: "subscription_started"
}

// events.wait -> wait_matched
export interface WaitMatchedResult {
  event: EventEnvelope
  type: "wait_matched"
}

// layout.export -> layout_export
export interface LayoutExportResult {
  layout: LayoutDescription
  type: "layout_export"
}

// layout.apply -> layout_apply
export interface LayoutApplyResult {
  layout: LayoutDescription
  type: "layout_apply"
}

// notification.show -> notification_show
export interface NotificationShowResult {
  reason: NotificationShowReason
  shown: boolean
  type: "notification_show"
}

export interface HerdrResultMap {
  'session.snapshot': SessionSnapshotResult
  'agent.list': AgentListResult
  'agent.get': AgentViewResult
  'agent.wait': AgentInfoResult
  'agent.explain': AgentExplainResult
  'agent.prompt': AgentPromptedResult
  'agent.send_keys': OkResult
  'pane.split': PaneInfoResult
  'pane.send_text': OkResult
  'pane.send_keys': OkResult
  'pane.read': PaneReadBranchResult
  'pane.wait_for_output': OutputMatchedResult
  'pane.report_agent': OkResult
  'pane.report_metadata': OkResult
  'pane.clear_agent_authority': OkResult
  'workspace.create': WorkspaceCreatedResult
  'events.subscribe': SubscriptionStartedResult
  'events.wait': WaitMatchedResult
  'layout.export': LayoutExportResult
  'layout.apply': LayoutApplyResult
  'notification.show': NotificationShowResult
}

// ---------- 错误体（CA-004） ----------
export interface HerdrErrorBody {
  code: string
  message: string
}

// ---------- 事件（CA-004） ----------
export type HerdrEventKind = "workspace_created" | "workspace_updated" | "workspace_metadata_updated" | "workspace_closed" | "workspace_renamed" | "workspace_moved" | "workspace_reordered" | "workspace_focused" | "worktree_created" | "worktree_opened" | "worktree_removed" | "tab_created" | "tab_closed" | "tab_renamed" | "tab_moved" | "tab_focused" | "pane_created" | "pane_closed" | "pane_updated" | "pane_focused" | "pane_moved" | "pane_output_changed" | "pane_exited" | "pane_agent_detected" | "pane_agent_status_changed" | "layout_updated"

export type HerdrEventData = {
  type: "workspace_created"
  workspace: WorkspaceInfo
} | {
  type: "workspace_updated"
  workspace: WorkspaceInfo
} | {
  type: "workspace_metadata_updated"
  workspace: WorkspaceInfo
} | {
  type: "workspace_closed"
  workspace?: WorkspaceInfo | Record<string, unknown> | null
  workspace_id: string
} | {
  label: string
  type: "workspace_renamed"
  workspace_id: string
} | {
  insert_index: number
  type: "workspace_moved"
  workspace_id: string
  workspaces: WorkspaceInfo[]
} | {
  before_workspace_id?: string | null
  type: "workspace_reordered"
  workspace_ids: string[]
  workspaces: WorkspaceInfo[]
} | {
  type: "workspace_focused"
  workspace_id: string
} | {
  type: "worktree_created"
  workspace: WorkspaceInfo
  worktree: WorktreeInfo
} | {
  already_open: boolean
  type: "worktree_opened"
  workspace: WorkspaceInfo
  worktree: WorktreeInfo
} | {
  forced: boolean
  type: "worktree_removed"
  workspace?: WorkspaceInfo | Record<string, unknown> | null
  workspace_id: string
  worktree: WorktreeInfo
} | {
  tab: TabInfo
  type: "tab_created"
} | {
  tab_id: string
  type: "tab_closed"
  workspace_id: string
} | {
  label: string
  tab_id: string
  type: "tab_renamed"
  workspace_id: string
} | {
  insert_index: number
  tab_id: string
  tabs: TabInfo[]
  type: "tab_moved"
  workspace_id: string
} | {
  tab_id: string
  type: "tab_focused"
  workspace_id: string
} | {
  pane: PaneInfo
  type: "pane_created"
} | {
  pane_id: string
  type: "pane_closed"
  workspace_id: string
} | {
  pane: PaneInfo
  type: "pane_updated"
} | {
  pane_id: string
  type: "pane_focused"
  workspace_id: string
} | {
  closed_tab_id?: string | null
  closed_workspace_id?: string | null
  created_tab?: TabInfo | Record<string, unknown> | null
  created_workspace?: WorkspaceInfo | Record<string, unknown> | null
  pane: PaneInfo
  previous_pane_id: string
  previous_tab_id: string
  previous_workspace_id: string
  type: "pane_moved"
} | {
  pane_id: string
  revision: number
  type: "pane_output_changed"
  workspace_id: string
} | {
  pane_id: string
  type: "pane_exited"
  workspace_id: string
} | {
  agent?: string | null
  final_status?: AgentStatus | Record<string, unknown> | null
  pane_id: string
  released?: boolean
  type: "pane_agent_detected"
  workspace_id: string
} | {
  agent?: string | null
  agent_status: AgentStatus
  display_agent?: string | null
  pane_id: string
  state_labels?: { [key: string]: string }
  title?: string | null
  type: "pane_agent_status_changed"
  workspace_id: string
} | {
  layout: PaneLayoutSnapshot
  type: "layout_updated"
}

export interface HerdrEvent {
  event: HerdrEventKind
  data: HerdrEventData
}

// ---------- 订阅事件（CA-004） ----------
export type HerdrSubscriptionEventKind = "pane.output_matched" | "pane.agent_status_changed" | "pane.scroll_changed"

export type HerdrSubscriptionEventData = PaneOutputMatchedEvent | PaneAgentStatusChangedEvent | PaneScrollChangedEvent

export interface HerdrSubscriptionEvent {
  event: HerdrSubscriptionEventKind
  data: HerdrSubscriptionEventData
}
